name: zip the chrome extension

on:
  workflow_dispatch:

jobs:
  zip_app:
    name: zip_app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Zip the app
        run: zip -rv9 rednote_helper_app.zip ./rednote_helper_app/

      - name: Archive zip_app production
        uses: actions/upload-artifact@v6
        with:
          name: rednote_helper_app
          path: ./*.zip
          if-no-files-found: error
